# show_downloads: true
google_analytics: G-GZNFK3DY0Z
theme: jekyll-theme-cayman
title: KuaiRand
description: "An Unbiased Sequential Recommendation Dataset with Randomly Exposed Videos"
github:
  is_project_page: true